# HLint configuration file
##########################

# Ignore warnings if the code is fine the way it is.
- ignore:
    name: "Avoid lambda using `infix`"
    within: "HsLua.Core.Primary"

- ignore:
    name: "Reduce duplication"
    within: "HsLua.Class.Pushable"

# Lua functions use snake_case, not camelCase
- ignore:
    name: "Use camelCase"
    within:
      - "Lua.Call"
      - "Lua.Userdata"
      - "HsLua.Module.Path"
      - "HsLua.Packaging.RenderingTests"

- modules:
  # Ensure names for qualified imports
  - {name: Data.ByteString, as: B}
  - {name: Data.ByteString.Char8, as: Char8}
  - {name: Data.Text, as: T}
  - {name: Foreign.Lua, as: Lua}


# Ban "module X(module X) where", to require a real export list
- warn: {name: Use explicit module export list}

# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
