sudo: false
language: haskell

# Speed builds up by caching install requirements
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

ghc:
  - '8.0'
  - '8.2'
  - '8.4.4'
  - '8.6.5'
  - '8.8.3'
  - '8.10.1'
