language: haskell

# Speed builds up by caching install requirements
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

matrix:
  include:
    ## Test Compilers
    # Test GHC 8.0.2
    - env: LUAVER=default
      ghc: 8.0.2
      cabal: 2.2

    # Test GHC 8.2.2
    - env: LUAVER=default
      ghc: 8.2.2
      cabal: 2.4

    # Test GHC 8.4.4
    - env: LUAVER=default
      ghc: 8.4.4
      cabal: 2.4

    # Test GHC 8.6
    - env: LUAVER=default
      ghc: 8.6.5
      cabal: 3.2

    # Test GHC 8.8
    - env: LUAVER=default
      ghc: 8.8.4
      cabal: 3.2

    # Test GHC 8.10
    - env: LUAVER=default
      ghc: 8.10.2
      cabal: 3.4

    ## Test system Lua
    # Test system Lua 5.3
    - env: LUAVER=5.3.5
      ghc: 8.8.4
      cabal: 3.2

  # mark build as successful as soon as all required successes are in.
  fast_finish: true

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
  - cabal update

install:
  - |
    printf "$(ghc --version)"
    printf " [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - cabal new-build --only-dependencies --enable-tests --disable-optimization

script:
  - CABAL_CONFIG_ARGS=""
  - |
    case "$LUAVER" in
      (lua-5*):
          # Install Lua
          wget http://www.lua.org/ftp/${LUAVER}.tar.gz
          tar -xf ${LUAVER}.tar.gz
          cd ${LUAVER}
          sed -i 's/^CFLAGS= -O2 -Wall/CFLAGS= -O2 -Wall -fPIC/' src/Makefile
          make linux
          make install INSTALL_TOP=${HOME}/usr
          cd ..

          # Compile and link using system-wide Lua
          printf "constraint: hslua +system-lua\n" > cabal.project.local
          printf "extra-include-dirs: ${HOME}/usr/include\n" >> cabal.project.local
          printf "extra-lib-dirs: ${HOME}/usr/lib\n" >> cabal.project.local
          ;;
      (*):
          cabal new-configure --enable-tests --disable-optimization
    esac
  - export LD_LIBRARY_PATH=${HOME}/usr/lib:$LD_LIBRARY_PATH
  - echo $CABAL_CONFIG_ARGS
  - cabal new-build
  - cabal new-test
  - cabal sdist
  # Run HLint
  - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
