sudo: false
language: c
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  # grab the appropriate GHC and cabal-install versions from hvr's PPA.
  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    compiler: "GHC 7.10.3"
    addons:
      apt:
        packages:
          - cabal-install-1.22
          - ghc-7.10.3
        sources: [hvr-ghc]

  - env: BUILD=cabal GHCVER=8.0.2 CABALVER=1.24
    compiler: "GHC 8.0.2"
    addons:
      apt:
        packages:
          - cabal-install-1.24
          - ghc-8.0.2
        sources: [hvr-ghc]

  - env: BUILD=cabal GHCVER=8.2.1 CABALVER=1.24
    compiler: "GHC 8.2.1"
    addons:
      apt:
        packages:
          - cabal-install-1.24
          - ghc-8.2.1
        sources: [hvr-ghc]

  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - env: BUILD=stack ARGS="--resolver lts-10"
    compiler: "stack 8.0.2"
    addons:
      apt:
        packages:
          - ghc-8.0.2
        sources: [hvr-ghc]

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  curl -L https://www.stackage.org/stack/linux-x86_64 | \
    tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- |
  case "$BUILD" in
    stack)
      stack --no-terminal --install-ghc $ARGS test --flag 'aeson:fast' --only-dependencies --fast
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      cabal install --only-dependencies --enable-tests --force-reinstalls --reorder-goals
      ;;
  esac

script:
- GHC_OPTIONS="-Wall -Werror"
- |
  case "$BUILD" in
    stack)
      stack --no-terminal test --haddock --no-haddock-deps --ghc-options="$GHC_OPTIONS"
      ;;
    cabal)
      cabal configure --enable-tests --ghc-options="$GHC_OPTIONS"
      cabal build
      cabal check
      cabal test --show-details=direct
      cabal copy
      cabal sdist
      SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && \
        (cd dist && cabal install --enable-tests --force-reinstalls "$SRC_TGZ")
      ;;
  esac
