language: haskell

# Speed builds up by caching install requirements
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

dist: focal

matrix:
  include:
    ## Test Compilers
    # Test GHC 8.0.2
    - ghc: 8.0.2
      cabal: 2.4

    # Test GHC 8.2.2
    - ghc: 8.2.2
      cabal: 2.4

    # Test GHC 8.4.4
    - ghc: 8.4.4
      cabal: 2.4

    # Test GHC 8.6
    - ghc: 8.6.5
      cabal: 3.2

    # Test GHC 8.8
    - ghc: 8.8.4
      cabal: 3.2

    # Test GHC 8.10
    - ghc: 8.10.2
      cabal: 3.4

    ## Test system Lua
    # Test system Lua 5.3
    - env: FLAGS="+hardcode-reg-keys +pkg-config +system-lua"
      ghc: 8.8.4
      cabal: 3.2
      addons:
        apt:
          packages:
            - liblua5.3-dev

  # mark build as successful as soon as all required successes are in.
  fast_finish: true

before_install:
  - cabal update

install:
  - cabal v2-build --only-dependencies --enable-tests --disable-optimization

script:
  - cabal v2-configure --flags "${FLAGS}" --enable-tests --disable-optimization
  - cabal v2-build
  - cabal v2-test
  - cabal v2-sdist
