build: off
clone_folder: "c:\\hslua"

environment:
  matrix:
    - STACK_VERSION: "windows-i386"
      STACK_ROOT: "c:\\sr32"
      STACK: "%STACK_ROOT%\\stack.exe"
      STACK_FLAGS: ""
    - STACK_VERSION: "windows-x86_64"
      STACK_ROOT: "c:\\sr64"
      STACK: "%STACK_ROOT%\\stack.exe"
      STACK_FLAGS: ""

matrix:
  fast_finish: true

cache:
  - "%STACK_ROOT%"

before_test:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

  - |
    %STACK% --version || curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/%STACK_VERSION% && 7z e stack.zip -o"%STACK_ROOT%" stack.exe

test_script:
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor
  - '%STACK% setup > nul'
  - '%STACK% path'
  - 'echo "" | %STACK% clean'
  - 'echo "" | %STACK% --no-terminal test %STACK_FLAGS%'
