build: off
clone_folder: "c:\\hslua"

environment:
  matrix:
    - STACK_VERSION: "windows-i386"
      STACK_ROOT: "c:\\sr32"
      STACK: "stack.exe"
      STACK_FLAGS: "--resolver=lts-22"
    - STACK_VERSION: "windows-x86_64"
      STACK_ROOT: "c:\\sr64"
      STACK: "stack.exe"
      STACK_FLAGS: "--resolver=lts-22"

matrix:
  fast_finish: true

cache:
  - "%STACK_ROOT%"

before_test:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

  - curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
  - 7z x stack.zip stack.exe
  # Copy file, symlinking is broken on Windows
  - 'copy /Y hslua-core\test\Test\Tasty\HsLua.hs tasty-hslua\src\Test\Tasty\HsLua.hs'

test_script:
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor
  - '%STACK% setup %STACK_FLAGS% > nul'
  - '%STACK% path'
  - 'echo "" | %STACK% clean'
  - 'echo "" | %STACK% --no-terminal test %STACK_FLAGS%'
