name: Lint

# Trigger the workflow on push or pull request, but only for the
# master branch
on:
  pull_request: {}
  push:
    paths-ignore:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - stack.yaml
      - .travis.yml

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download HLint
        run: |
          curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh > ~/hlint
          chmod +x ~/hlint

      - name: Check sources
        run: |
          ~/hlint .
